- name: Create Spot Checker Task Definition
  ecs_taskdefinition:
    containers:
    - name: "spot-checker"
      volumesFrom: []
      memory: 128
      essential: true
      mountPoints: []
      environment: "{{ENVIRONMENT}}"
      logConfiguration: {
        'logDriver': 'awslogs',
        'options': {
          'awslogs-group': '{{SPOT_CHECKER_SQS_AWS_LOG_GROUP}}',
          'awslogs-region': '{{REGION}}',
          'awslogs-stream-prefix': '{{SPOT_CHECKER_SQS_AWS_LOG_PREFIX}}'
        }
      }
      workingDirectory: '/app/spotchecker'
      image: "{{AWS_ACCOUNT_ID}}.dkr.ecr.eu-west-1.amazonaws.com/{{PARKING_REPO}}:{{TAG}}"
      command: ['node', 'app.js']
      cpu: 0
    family: "{{SPOT_CHECKER_SQS_TASK_DEFINITION}}"
    network_mode: "host"
    state: present
  register: task_output
- set_fact:
    updateClusterService: {'service': '{{SPOT_CHECKER_SQS_CONSUMER_SERVICE}}', 'taskDefinitionArn': '{{task_output.taskdefinition.taskDefinitionArn}}', 'family': '{{SPOT_CHECKER_SQS_TASK_DEFINITION}}'}
- debug: var=task_output